In [127]:
import glob
import pandas as pd
import os
import sys
import numpy as np
import math

In [128]:
fall_precovid  = {
    1:17,
    2:15,
    3:0,
    4:0,
    5:95,
    6:5,
    7:0,
    8:20,
    9:0,
    10:0,
    11:19,
    14:0,
    15:11,
    16:14,
    17:37,
    18:38,
    19:73,
    20:65,
    21:70,
    22:35,
    23:93,
    24:100,
    25:78,
    26:68,
    27:26,
    28:96,
    29:54,
    30:8,
    31:63,
    32:30,
    33:87,
    34:101,
    35:94,
    36:69,
    37:45,
    38:36,
    39:105,
    40:47,
    41:59,
    42:39,
    43:53,
    44:46,
    45:75,
    46:16,
    47:102,
    48:74,
    49:12,
    50:23,
    51:32,
    53:98,
    54:88,
    55:13,
    56:64,
    57:28,
    58:25,
    59:33,
    60:86,
    61:92,
    62:58,
    63:34,
    64:97,
    65:31,
    66:89,
    67:72,
    68:84,
    69:50,
    70:83,
    71:3,
    72:29,
    74:42,
    75:85,
    76:90,
    77:52,
    78:21,
    79:81,
    80:49,
    81:67,
    82:0,
    83:0,
    84:18
}

In [129]:
data = pd.read_csv('../data_access/process_survey_data/processed_data.csv')
search_files = glob.glob('/home/anis/fall2019/data/summer2020-Data/processed/search+youtube/*.csv')
# glob('/home/anis/fall2019/data/summer2020-Data/processed/search+youtube/*.csv')
postCovid_preCovid = {}
for f in search_files:
    now, previous = f.split('/')[-1].split('.')[0].split('_')
    postCovid_preCovid[int(now)] = int(previous)

In [130]:
data.lockdown_talking_people.value_counts()

1    34
2     7
3     1
Name: lockdown_talking_people, dtype: int64

In [139]:
 postCovid_preCovid

{8: 41,
 10: 34,
 1: 22,
 24: 64,
 19: 28,
 36: 63,
 30: 75,
 21: 8,
 7: 43,
 18: 11,
 22: 45,
 5: 19,
 35: 58,
 28: 16,
 17: 40,
 23: 70,
 9: 66,
 3: 77,
 12: 32,
 29: 30,
 15: 39,
 2: 27,
 16: 5,
 14: 31,
 27: 47,
 13: 24,
 11: 38,
 33: 62,
 4: 50,
 31: 84,
 32: 17,
 34: 25,
 25: 79,
 20: 26,
 26: 85,
 37: 82,
 6: 65}

In [131]:
org_column_names = data.columns.tolist()
org_column_name_to_index = {}
for i,name in enumerate(org_column_names):
    org_column_name_to_index[name] = i

In [145]:
container = []
for index,row in data.iterrows():
    nd = {}
    nd['record_id'] = row.record_id
    
    nd['sid_during_covid'] = row.record_id
    if row.record_id in postCovid_preCovid:
        nd['sid_pre_covid'] = postCovid_preCovid[row.record_id]
    else:
        nd['sid_pre_covid'] = 9999
        
    if nd['sid_pre_covid'] == 9999:
        nd['sid_2019'] = -9999
    else:
        fall_19_id = int(postCovid_preCovid[row.record_id])
        if fall_19_id in fall_precovid:
            nd['sid_2019'] = fall_precovid[fall_19_id]
        else:
            nd['sid_2019'] = 9999

    #1, Alabama | 2, Alaska | 3, Arizona | 4, Arkansas | 5, California | 6, Colorado | 7, Connecticut | 8, Delaware | 9, Florida | 10, Georgia | 11, Hawaii | 12, Idaho | 13, Illinois | 14, Indiana | 15, Iowa | 16, Kansas | 17, Kentucky | 18, Louisiana | 19, Maine | 20, Maryland | 21, Massachusetts | 22, Michigan | 23, Minnesota | 24, Mississippi | 25, Missouri | 26, Montana | 27, Nebraska | 28, Nevada | 29, New Hampshire | 30, New Jersey | 31, New Mexico | 32, New York | 33, North Carolina | 34, North Dakota | 35, Ohio | 36, Oklahoma | 37, Oregon | 38, Pennsylvania | 39, Rhode Island | 40, South Carolina | 41, South Dakota | 42, Tennessee | 43, Texas | 44, Utah | 45, Vermont | 46, Virginia | 47, Washington | 48, West Virginia | 49, Wisconsin | 50, Wyoming | 51, American Samoa | 52, Guam | 53, The Northern Mariana Islands | 54, Puerto Rico | 55, U.S. Virgin Islands
    nd['current_living_state'] = row.current_living_state
    nd['num_people_living_with'] = row.num_people_living_with
    
    nd['current_living_state'] = row.current_living_state
    
    nd['someone_to_talk_to'] = row.someone_to_talk_to
    nd['emergency_living'] = row.emergency_living
    nd['money_for_needs'] = row.money_for_needs
    nd['eat_less'] = row.eat_less
    nd['borrow_money'] = row.borrow_money
    nd['lose_housing'] = row.lose_housing
    

    nd['suicide_ideation'] = row.suicide
    nd['si_timeline'] = row.si_timeline
    
    nd['phq9_score'] = row.phq9_score
    nd['gad7_score'] = row.gad7_score  
    nd['selfesteem_score'] = row.selfesteem_score
    nd['num_classes_made_pass_fail'] = row.classes_pass_fail
    nd['promotehealth_timestamp'] = row.promotehealth_timestamp
    
    if row.living_situation_before in [1,2]:
        nd['living_b4_with_family'] = 1
    else:
        nd['living_b4_with_family'] = 0
    
    if row.living_situation_before in [3,4,5,6,7,8,9]:
        nd['living_b4_in_univ'] = 1
    else:
        nd['living_b4_in_univ'] = 0
    
    if row.living_with_whom in [1,2,3]:
        nd['living_wth_family'] = 1
    else:
        nd['living_wth_family'] = 0
    
    
    if row.living_with_whom in [4,5,6]:
        nd['not_living_wth_family'] = 1
    else:
        nd['not_living_wth_family'] = 0
    
    if row.phq9_final == 0:
        
        nd['no_dep_difficulty'] = 1
    else:
        nd['no_dep_difficulty'] = 0
    
    
    
    if 'nan' in str(row.si_timeline) == False:
        nd['si_within_last_3months'] = 1
    else:
        nd['si_within_last_3months'] = 0


    if row.politically_involved in [1 , 2]:
        nd['politically_involved'] = 1
    else:
        nd['politically_involved'] = 0

    if row.politically_involved in [3]:
        nd['politically_neutral'] = 1
    else:
        nd['politically_neutral'] = 0

    if row.politically_involved in [4,5]:
        nd['politically_not_involved'] = 1
    else:
        nd['politically_not_involved'] = 0

        
    if row.trump_approval in [1,2]:
        nd['suport_govt_response'] = 1
    else:
        nd['suport_govt_response'] = 0    

        
    if row.vote in [1,2]:
        nd['vote_for_Trump'] = 1
    else:
        nd['vote_for_Trump'] = 0        
        
    if row.after_corona_politics in [1]:
        nd['more_politically_engaged_since_covid'] = 1
    else:
        nd['more_politically_engaged_since_covid'] = 0        
        
    if row.employment == 1:
        nd['family_job_affected'] = 1
    else:
        nd['family_job_affected'] = 0
        
        
    if row.summer_job_affected == 1:
        nd['summer_job_affected'] = 1
    else:
        nd['summer_job_affected'] = 0  
        


    if row.lockdown_seeing_fam in [1,2,3]:
        nd['inperson_seeing_fam_during_lockdown'] = 1
    else:
        nd['inperson_seeing_fam_during_lockdown'] = 0

    if row.lockdown_seeing_friends in [1,2,3]:
        nd['inperson_seeing_bfgf_lockdown'] = 1
    else:
        nd['inperson_seeing_bfgf_lockdown'] = 0

    # freq = daily and weekly
    if row.lockdown_talking_people in [1,2]:
        nd['frequently_talk_to_fam_during_lockdown'] = 1
    else:
        nd['frequently_talk_to_fam_during_lockdown'] = 0
        
        
    if row.smoking_freq_lockdown in [1,2,3]:
        nd['smoking_freq_during_lockdown'] = 1
    else:
        nd['smoking_freq_during_lockdown'] = 0


    if row.smoking_freq_change == 1:
        nd['smoking_freq_increased'] = 1
    else:
        nd['smoking_freq_increased'] = 0
        
        
    if row.recreational_use in [1,2,3]:
        nd['freq_use_rec_substances_during_lockdown'] = 1
    else:
        nd['freq_use_rec_substances_during_lockdown'] = 0


    if row.recreational_use_change == 1:
        nd['rec_substances_usage_increased'] = 1
    else:
        nd['rec_substances_usage_increased'] = 0




    if row.sleep_change_lockdown == 1:
        nd['sleep_increase_due_to_corona'] = 1
    else:
        nd['sleep_increase_due_to_corona'] = 0

    if row.sleep_change_lockdown == 2:
        nd['sleep_decreased_due_to_corona'] = 1
    else:
        nd['sleep_decreased_due_to_corona'] = 0

    if row.sleep_change_lockdown == 3:
        nd['sleep_unchanged'] = 1
    else:
        nd['sleep_unchanged'] = 0


    if row.family_business == 1:
        nd['family_business_affected'] = 1
    else:
        nd['family_business_affected'] = 0


    if row.infected == 2:
        nd['no_covid_infection'] = 1
    else:
        nd['no_covid_infection'] = 0


    if row.infected == 1:
        nd['infected_by_covid'] = 1
    else:
        nd['infected_by_covid'] = 0

    if row.stressed_covid in [0,1,2]:
        nd['stress_dueto_corona'] = 1
    else:
        nd['stress_dueto_corona'] = 0


    if row.worried_covid in [0,1,2]:
        nd['future_corona_inf_worry'] = 1
    else:
        nd['future_corona_inf_worry'] = 0

    if row.effect_on_friends in [0,1,2]:
        nd['worried_abt_friends'] = 1
    else:
        nd['worried_abt_friends'] = 0


    if row.essential_worker in [1]:
        nd['essential_worker_u_or_fam'] = 1
    else:
        nd['essential_worker_u_or_fam'] = 0       
        
        
    if row.be_healthy in [1,2,3]:
        nd['practice_healthy_living_during_lockdown'] = 1
    else:
        nd['practice_healthy_living_during_lockdown'] = 0
        
    if row.improve_spirit in [1,2,3]:
        nd['practice_improve_spirit_during_lockdown'] = 1
    else:
        nd['practice_improve_spirit_during_lockdown'] = 0        
        
    if row.improve_spirit in [1,2,3]:
        nd['lack_of_person_space_during_lockdown'] = 1
    else:
        nd['lack_of_person_space_during_lockdown'] = 0           
        
    if row.academic_work_lockdown in [1,2]:
        nd['study_less_3hr_day_during_lockdown'] = 1
    else:
        nd['study_less_3hr_day_during_lockdown'] = 0
    if row.academic_work_hr_before in [1,2]:
        nd['study_less_3hr_day_before_lockdown'] = 1
    else:
        nd['study_less_3hr_day_before_lockdown'] = 0
    if row.online_motivate in [1,2]:
        nd['lack_of_motivation_towards_online_edu'] = 1
    else:
        nd['lack_of_motivation_towards_online_edu'] = 0

    if row.online_difficulty in [1,2]:
        nd['find_online_learning_difficult'] = 1
    else:
        nd['find_online_learning_difficult'] = 0

    if '11' in row.lockdown_entertainment:
        nd['napping_in_free_time_during_lockdown'] = 1
    else:
        nd['napping_in_free_time_during_lockdown'] = 0

    if '10' in row.lockdown_entertainment or '6' in row.lockdown_entertainment or '9' in row.lockdown_entertainment:
        nd['pass_time_on_digital_media'] = 1
    else:
        nd['pass_time_on_digital_media'] = 0


    if '1' in row.lockdown_entertainment or '2' in row.lockdown_entertainment or '3' in row.lockdown_entertainment or '4' in row.lockdown_entertainment or '7' in row.lockdown_entertainment or '5' in row.lockdown_entertainment:
        nd['pass_time_doing_activites'] = 1
    else:
        nd['pass_time_doing_activites'] = 0        
    
    
    
    if row.online_worth in [1,2]:
        nd['online_class_worth_it'] = 1
    else:
        nd['online_class_worth_it'] = 0

    if row.fall_online in [1,2]:
        nd['will_take_online_classes_in_fall'] = 1
    else:
        nd['will_take_online_classes_in_fall'] = 0

    if row.academic_perf == 3:
        nd['academic_perf_didnt_change_due_to_covid'] = 1
    else:
        nd['academic_perf_didnt_change_due_to_covid'] = 0


    if row.substances_before in [1,2,3]:
        nd['use_rec_substances_frequently_before_covid'] = 1
    else:
        nd['use_rec_substances_frequently_before_covid'] = 0


    if row.smokling_before in [1,2,3]:
        nd['smoke_frequently_before_covid'] = 1
    else:
        nd['smoke_frequently_before_covid'] = 0


    if row.healthy_before in [1,2,3]:
        nd['practice_healthy_living_before_lockdown'] = 1
    else:
        nd['practice_healthy_living_before_lockdown'] = 0

    if row.improve_spirit_before in [1,2,3]:
        nd['practice_improve_spirit_before_lockdown'] = 1
    else:
        nd['practice_improve_spirit_before_lockdown'] = 0 
   
    
    
    
    
    container.append(nd)
    

d = pd.DataFrame(container)

In [146]:
d

,record_id,sid_during_covid,sid_pre_covid,sid_2019,current_living_state,num_people_living_with,someone_to_talk_to,emergency_living,money_for_needs,eat_less,...,napping_in_free_time_during_lockdown,pass_time_on_digital_media,pass_time_doing_activites,online_class_worth_it,will_take_online_classes_in_fall,academic_perf_didnt_change_due_to_covid,use_rec_substances_frequently_before_covid,smoke_frequently_before_covid,practice_healthy_living_before_lockdown,practice_improve_spirit_before_lockdown
0,1,1,22,35,5.0,4,0,1,0,0,...,0,1,1,0,0,1,0,0,1,1
1,2,2,27,26,32.0,6,1,1,1,0,...,0,1,1,0,1,0,0,0,0,1
2,3,3,77,52,32.0,2,1,1,1,0,...,1,1,1,0,0,0,0,0,1,1
3,4,4,50,23,32.0,1,1,0,1,0,...,1,1,1,0,1,1,0,0,0,1
4,5,5,19,73,32.0,1,1,1,1,0,...,0,1,1,0,0,1,0,0,1,0
5,6,6,65,31,32.0,1,1,1,1,0,...,0,1,1,0,0,1,1,0,0,1
6,7,7,43,53,32.0,1,1,1,1,0,...,0,1,1,0,0,0,0,0,1,1
7,8,8,41,59,32.0,2,1,1,1,0,...,1,1,1,0,0,0,1,0,1,1
8,9,9,66,89,30.0,4,1,1,1,0,...,0,1,1,0,0,1,1,0,1,1
9,10,10,34,101,32.0,5,1,1,1,1,...,0,1,1,0,0,0,0,0,1,1
10,11,11,38,36,5.0,3,1,1,1,0,...,0,1,1,0,1,0,0,0,1,1
11,12,12,32,30,NaN,4,1,1,1,0,...,1,1,1,0,1,0,1,0,1,1
12,13,13,24,100,9.0,6,0,1,1,0,...,0,1,1,0,0,1,0,0,0,1
13,14,14,31,63,32.0,1,1,1,1,0,...,1,1,1,0,0,1,0,0,1,0
14,15,15,39,105,32.0,1,1,1,1,0,...,0,1,1,0,1,0,0,0,1,1
15,16,16,5,95,32.0,6,0,1,0,1,...,1,1,1,0,1,1,0,0,1,1
16,17,17,40,47,32.0,1,1,1,1,0,...,1,1,1,1,1,1,0,0,1,1
17,18,18,11,19,32.0,6,1,1,1,0,...,1,1,1,0,1,0,0,0,0,1
18,19,19,28,96,32.0,3,0,1,1,1,...,0,1,0,0,0,0,1,0,1,1
19,20,20,26,68,47.0,2,1,1,1,0,...,1,1,1,1,1,1,0,0,1,1
20,21,21,8,20,32.0,4,1,1,1,1,...,0,1,1,0,1,1,1,0,1,1
21,22,22,45,75,38.0,3,1,1,1,0,...,1,1,1,0,1,0,0,0,1,1
22,23,23,70,83,32.0,3,1,1,1,0,...,1,1,1,0,1,0,1,0,1,1
23,24,24,64,97,32.0,6,1,0,1,1,...,0,1,1,0,1,0,1,0,1,1
24,25,25,79,81,43.0,3,1,1,1,0,...,1,1,1,0,1,0,1,0,1,1
25,26,26,85,9999,32.0,2,1,1,0,1,...,1,1,1,1,0,0,1,1,1,1
26,27,27,47,102,7.0,4,1,1,1,0,...,0,0,1,0,0,0,1,1,1,1
27,28,28,16,14,32.0,3,1,1,1,0,...,0,1,1,0,0,0,1,0,1,1
28,29,29,30,8,21.0,4,1,1,1,0,...,0,1,1,1,1,0,1,0,1,1
29,30,30,75,85,32.0,4,1,1,1,0,...,0,1,1,0,1,1,0,0,1,1
30,31,31,84,18,7.0,4,1,1,1,0,...,0,1,1,0,0,1,0,0,1,1
31,32,32,17,37,32.0,3,1,1,1,0,...,0,1,1,0,1,0,0,0,1,0
32,33,33,62,58,32.0,2,1,1,1,0,...,1,1,1,0,0,0,0,0,1,1
33,34,34,25,78,32.0,1,1,1,1,1,...,1,1,1,0,0,1,0,0,1,1
34,35,35,58,25,39.0,3,1,1,1,0,...,1,1,1,0,0,1,1,1,1,1
35,36,36,63,34,32.0,4,1,1,1,1,...,1,1,1,0,1,1,0,0,1,1
36,37,37,82,0,32.0,3,0,1,1,0,...,1,1,1,0,1,1,0,0,1,1
37,38,38,9999,-9999,30.0,3,1,1,1,0,...,1,1,1,0,0,0,0,0,1,1
38,40,40,9999,-9999,54.0,4,1,1,0,0,...,0,1,1,0,0,0,1,0,1,1
39,41,41,9999,-9999,39.0,5,1,1,1,0,...,0,1,1,0,1,1,0,0,1,1
40,42,42,9999,-9999,32.0,3,1,1,1,1,...,1,1,1,0,0,1,0,0,1,1
41,43,43,9999,-9999,32.0,4,1,1,1,0,...,1,1,1,0,0,1,0,0,1,1

In [147]:
d.to_csv('ready_survey_data.csv',index=False)